routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('s');


Auth::routes();

Route::get('/show', [\App\Http\Controllers\HomeController::class, 'show']);
Route::get('/showOne', [\App\Http\Controllers\HomeController::class, 'getOne']);
Route::get('/create', [\App\Http\Controllers\HomeController::class, 'create']);
Route::get('/updateProduct', [\App\Http\Controllers\HomeController::class, 'updateProduct']);
Route::get('/getCategory', [\App\Http\Controllers\HomeController::class, 'getCategory']);
Route::get('/createVarian', [\App\Http\Controllers\HomeController::class, 'createVarian']);
Route::get('/showVarian', [\App\Http\Controllers\HomeController::class, 'showVarian']);
Route::get('/createAttribute', [\App\Http\Controllers\HomeController::class, 'createAttribute']);
Route::get('/createOption', [\App\Http\Controllers\HomeController::class, 'createOption']);
Route::get('/order', [\App\Http\Controllers\HomeController::class, 'order']);
Route::get('/orderCart', [\App\Http\Controllers\HomeController::class, 'orderCart']);
Route::get('/order/destroy/{id}', [\App\Http\Controllers\HomeController::class, 'deleteCart'])->name('delete.cart');
Route::get('/customer', [\App\Http\Controllers\HomeController::class, 'showCustomer']);
Route::get('/report', [\App\Http\Controllers\HomeController::class, 'report']);
Route::get('/showAttribute', [\App\Http\Controllers\HomeController::class, 'showAttribute']);

Route::middleware(['auth'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::get('/pos', [App\Http\Controllers\HomeController::class, 'pos'])->name('pos');

    Route::post('/posSearch/', [App\Http\Controllers\HomeController::class, 'posSearch'])->name('pos.search');
    Route::get('/pos/variable/{id}', [App\Http\Controllers\HomeController::class, 'posVariable'])->name('posVariable');
    Route::get('/hold/{customer_id}', [App\Http\Controllers\HomeController::class, 'holdView'])->name('holdView');

    //Route::get('/expense', [App\Http\Controllers\HomeController::class, 'expense'])->name('expense');
    Route::get('/home/{filter}', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboardFilter');
    Route::get('actionCart/{name}/{price}/{product_id}/{variant_id}', [App\Http\Controllers\HomeController::class, 'actionCart'])->name('actionCart');

    Route::post('/updateQty', [\App\Http\Controllers\HomeController::class, 'updateQty'])->name('updateQty');
    Route::post('/getDiscount', [\App\Http\Controllers\HomeController::class, 'getDiscount']);

    Route::get('/totalPrice', [\App\Http\Controllers\HomeController::class, 'totalPrice'])->name('totalPrice');

    Route::post('/hold', [\App\Http\Controllers\HomeController::class, 'hold'])->name('hold');

    Route::post('/createCustomer', [\App\Http\Controllers\HomeController::class, 'createCustomer'])->name('createCustomer');
    Route::post('/createOrder', [\App\Http\Controllers\HomeController::class, 'createOrder'])->name('createOrder');

    Route::get('/printInvoice/{id}', [\App\Http\Controllers\HomeController::class, 'printInvoice'])->name('printInvoice');
    Route::get('/printShipping/{id}', [\App\Http\Controllers\HomeController::class, 'printShipping'])->name('printShipping');

    Route::get('/printLabel/{type}/{id}', [\App\Http\Controllers\HomeController::class, 'printLabel'])->name('printLabel');
    Route::get('/transaction', [\App\Http\Controllers\HomeController::class, 'transaction'])->name('transaction');

    //Route::group(['prefix'=>'products','as'=>'products.','middleware'=>'auth'], function(){
    Route::group(['prefix' => 'products', 'as' => 'products.', 'middleware' => 'auth'], function () {
        Route::get('/import', [App\Http\Controllers\ProductController::class, 'import'])->name('import');
        Route::post('/importAction', [App\Http\Controllers\ProductController::class, 'importAction'])->name('importAction');
        Route::get('/', [App\Http\Controllers\ProductController::class, 'index'])->name('index');
        Route::get('/edit/{id}', [App\Http\Controllers\ProductController::class, 'edit'])->name('edit');
        Route::post('/update/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('update');
        Route::get('/destroy/{id}', [App\Http\Controllers\ProductController::class, 'destroy'])->name('destroys');
        Route::get('/a/create', [\App\Http\Controllers\ProductController::class, 'create'])->name('create');
        Route::post('/a/create/post', [\App\Http\Controllers\ProductController::class, 'store'])->name('store');

        Route::get('/label', [App\Http\Controllers\ProductController::class, 'label'])->name('label');
        Route::get('/labelVariant/{id}', [App\Http\Controllers\ProductController::class, 'labelVariant'])->name('labelVariant');
        Route::get('/actionLabel/{id}/{name}/{price}', [App\Http\Controllers\ProductController::class, 'actionLabel'])->name('actionLabel');
        Route::post('/labelPrint', [App\Http\Controllers\ProductController::class, 'labelPrint'])->name('labelPrint');
        Route::get('/clear/label', [App\Http\Controllers\ProductController::class, 'clearLabel'])->name('clear.label');

        // Route::get('/', [App\Http\Controllers\ProductController::class, 'index'])->name('index');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.', 'middleware' => 'auth'], function () {
        Route::get('/import', [App\Http\Controllers\CategoryController::class, 'import'])->name('import');
        Route::get('/{page}', [App\Http\Controllers\CategoryController::class, 'index'])->name('index');
        Route::get('/destroy/{id}', [App\Http\Controllers\CategoryController::class, 'destroy'])->name('destroys');
        Route::get('/a/create', [\App\Http\Controllers\CategoryController::class, 'create'])->name('create');
        Route::post('/store', [\App\Http\Controollers\CategoryController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [\App\Http\Controllers\CategoryController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [\App\Http\Controllers\CategoryController::class, 'update'])->name('update');

        Route::get('/', [App\Http\Controllers\CategoryController::class, 'index'])->name('index');
    });
    Route::get('expense/destroys/{id}', [App\Http\Controllers\ExpenseController::class, 'destroy'])->name('expense.destroys');
    Route::resource('expense',\App\Http\Controllers\ExpenseController::class);

    Route::get('discount/destroys/{id}', [App\Http\Controllers\DiscountController::class, 'destroy'])->name('discount.destroys');
    Route::resource('discount',\App\Http\Controllers\DiscountController::class);

    Route::get('users/destroys/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroys');
    Route::resource('users',\App\Http\Controllers\UserController::class);
});

resources/views/dashboard/alert.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('danger'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        Please check the form below for errors
    </div>
@endif

resources/views/dashboard/home.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="row">
        <div class="col-md-6">
            <h1>Dashboard</h1>
        </div>
        <div class="col-md-6" style="text-align: end;padding-right: 100px">
            <div class="btn-group">
                <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown">Filter
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{route('dashboard')}}">Today</a>
                    <a class="dropdown-item" href="{{route('dashboardFilter','yesterday')}}">Yesterday</a>
                    <a class="dropdown-item" href="{{route('dashboardFilter','last7day')}}">Last 7 day</a>
                    <a class="dropdown-item" href="{{route('dashboardFilter','last30day')}}">last 30 day</a>
                    <a class="dropdown-item" href="{{route('dashboardFilter','thisMonth')}}">this month</a>
                    <a class="dropdown-item" href="#">last month</a>
                </div>
            </div>
        </div>
    </div>
{{--    <link rel="stylesheet" href="{{asset('uplot/uPlot.min.css')}}">--}}

@stop

@section('content')
    <div class="row">
        <div class="col-md-3 col-sm-6 col-12">
            <div class="info-box">
                <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                <div class="info-box-content">
                <span class="info-box-text">Total sales<span>
                <span class="info-box-number">$ {{$data['total_sales']}}</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">
            <div class="info-box">
                <span class="info-box-icon bg-success"><i class="far fa-flag"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">net</span>
                    <span class="info-box-number"><b>$</b> {{ ($net <= 0 ) ?'0' : $net}}</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">

            <div class="info-box">
                <span class="info-box-icon bg-warning"><i class="far fa-copy"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">invoice due</span>
                    <span class="info-box-number">13,648</span>
                </div>
                <!-- /.info-box-content -->
            </div>

        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">
            <div class="info-box">
                <span class="info-box-icon bg-danger"><i class="far fa-star"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">total purhase</span>
                    <span class="info-box-number">93,139</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>88
        <!-- /.col -->
    </div>
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Line Chart</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div>
                <canvas id="myChart"></canvas>
            </div>
        </div>
        <!-- /.card-body -->
    </div>

@stop

@section('js')
{{--    <script src="{{asset('uplot/uPlot.iife.min.js')}}"></script>--}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>

<script>
    const labels = [

        @foreach($dates as $a)
            '{{$a}}',
        @endforeach
    ];

    const data = {
        labels: labels,
        datasets: [{
            label: 'My First dataset',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: [
            @foreach($totals as $total)
                {{(int)$total->sales}},
                @endforeach
            ],
        }]
    };

    const config = {
        type: 'line',
        data: data,
        options: {}
    };
    const myChart = new Chart(
        document.getElementById('myChart'),
        config
    );
</script>

@stop

resources/views/dashboard/label.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')

{{--    <link rel="stylesheet" href="{{asset('uplot/uPlot.min.css')}}">--}}

@stop

@section('content')

    {{-- <h1>List Produk</h1>--}}
    <div class="card">
        <div class="card-body">
            <center>
            <a href="{{route('products.clear.label')}}" class="btn btn-danger">clear</a>
            </center>
            <form action="{{route('products.labelPrint')}}" method="post">
                @csrf
                @foreach($labels as $label )
               <div class="row">
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">Name Product</label>
                           <input type="text" name="name[]" value="{{$label->name}}"  id="inputName" class="form-control" readonly>
                       </div>
                   </div>
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">Unit Price</label>
                           <input type="text" name="unit_pirce[]" value="{{$label->unit_pirce}}"  id="inputName" class="form-control" readonly>
                       </div>
                   </div>
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">qty</label>
                           <input type="text" name="qty[]" value="{{$label->qty}}" id="inputName" class="form-control">
                       </div>
                   </div>
               </div>
                @endforeach
                <center><button type="submit" class="btn btn-success">Print</button></center>
            </form>
        </div>
    </div>
    <br><br>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Striped Full Width Table</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>
                        <span class="info-box-icon"><i class="far fa-image"></i></span>
                    </th>
                    <th>Name</th>

                    <th>variant</th>
                    <th>code</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody>
                {{-- {{$i=1}}--}}
                @foreach($products as $product)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><img src="{{$product->images[0]->src}}" width="50" height="50"></td>
                        <td>{{$product->name}}</td>

                        <td>{{$product->type}}</td>
                        <td>
                        {!! DNS1D::getBarcodeHTML('dwqdqw', "C128",1.4,22) !!}

                        {{--                    @foreach($product->tags as $tag)--}}
                        {{--                        {{$tag->name}},--}}
                        {{--                        @endforeach--}}
                        {{--                    </td>--}}
                        <td>
                            @if($product->type=='simple')
                            <div class="btn-group">
                                <a href="{{route('products.actionLabel',[$product->id,$product->name,$product->price])}}" class="btn btn-info">
                                    <i class="fas fa-plus"></i>
                                </a>
                            </div>
                            @else
                                <div class="btn-group">
                                    <a href="{{route('products.labelVariant',[$product->id])}}" class="btn btn-info">
                                        show variant
                                    </a>
                                </div>
                            @endif
                        </td>

                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    {{ $products->links('vendor.pagination.bootstrap-4') }}


    <!-- /.card-body -->
        <!-- <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
            </ul>
        </div> -->

    </div>
@stop

@section('js')
@stop

resources/views/dashboard/labelVariant.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')

{{--    <link rel="stylesheet" href="{{asset('uplot/uPlot.min.css')}}">--}}

@stop

@section('content')

    {{-- <h1>List Produk</h1>--}}
    <div class="card">
        <div class="card-body">
            <center>
                <a href="{{route('products.clear.label')}}" class="btn btn-danger">clear</a>
            </center>

            <form action="{{route('products.labelPrint')}}" method="post">
                @csrf
                @foreach($labels as $label )
               <div class="row">
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">Name Product</label>
                           <input type="text" name="name[]" value="{{$label->name}}"  id="inputName" class="form-control" readonly>
                       </div>
                   </div>
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">Unit Price</label>
                           <input type="text" name="unit_pirce[]" value="{{$label->unit_pirce}}"  id="inputName" class="form-control" readonly>
                       </div>
                   </div>
                   <div class="col-md-4">
                       <div class="form-group">
                           <label for="inputName">qty</label>
                           <input type="text" name="qty[]" value="{{$label->qty}}" id="inputName" class="form-control">
                       </div>
                   </div>
               </div>
                @endforeach
                <center><button type="submit" class="btn btn-success">Print</button></center>
            </form>
        </div>
    </div>
    <br><br>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Striped Full Width Table</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>

                    <th>Name</th>

                    <th>variant</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody>
                {{-- {{$i=1}}--}}
{{--                @dd()--}}
                @foreach($products as $product)
                    <tr>
                        <td>{{$loop->iteration}}</td>

                        <td>{{$get->name.' - '.$product->attributes[0]->option}}</td>
                        <td>{{$product->attributes[0]->option}}</td>

                        <td>
                            <div class="btn-group">
                                <a href="{{route('products.actionLabel',[$product->id,$get->name.' - '.$product->attributes[0]->option,$product->price])}}" class="btn btn-info">
                                    <i class="fas fa-plus"></i>
                                </a>
                            </div>
                        </td>

                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>


    <!-- /.card-body -->
        <!-- <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
            </ul>
        </div> -->

    </div>
@stop

@section('js')
@stop

resources/views/dashboard/pos.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')

{{--    <link rel="stylesheet" href="{{asset('uplot/uPlot.min.css')}}">--}}

@stop

@section('content')
<div class="row pt-2">
    <div class="col-md-3" style="background-color: white;  position: relative; height: 90vh">
        @include('layouts.cart')

    </div>
    <div class="col-md-9">

        <div class="container-fluid">
        <h2 class="text-center display-4">Search</h2>
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <form action="{{route('pos.search')}}" method="post">
                    @csrf
                    <div class="input-group">
                        <input type="search" name="search" class="form-control form-control-lg" placeholder="Type your keywords here">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-lg btn-default">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

        <center>
        <div class="row mt-4">
            @foreach($products as $product)

            <div class="col-md-4">
                <a href="{{($product->type == 'variable') ? route('posVariable',$product->id) : route('actionCart',[$product->name,$product->regular_price,$product->id,'simple'])}}">
                <div class="card" style="width: 15rem;">
                    <img class="card-img-top" src="{{$product->images[0]->src}}">
                    <div class="card-body">
                        <h5 class="card-title"> {{$product->type}} - {{$product->name}}</h5>
                    </div>
                </div>
                </a>
            </div>
            @endforeach

        </div>
            {{ $products->links('vendor.pagination.bootstrap-4') }}

        </center>

    </div>
</div>
@stop

@section('js')
@stop

resources/views/dashboard/posVariable.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')

{{--    <link rel="stylesheet" href="{{asset('uplot/uPlot.min.css')}}">--}}

@stop

@section('content')
<div class="row pt-2">
    <div class="col-md-3" style="background-color: white;  position: relative; height: 90vh">
        @include('layouts.cart')

    </div>
    <div class="col-md-9">
        <center>
        <div class="row mt-4">
            @foreach($products as $product)
                <div class="col-md-4">
                    <a href="{{route('actionCart',[$get->name.' - '.$product->attributes[0]->option,$product->regular_price,$get->id,$product->id])}}">
                    <div class="card" style="width: 15rem;">
                        <img class="card-img-top" src="{{$get->images[0]->src}}">
                        <div class="card-body">
                            <h5 class="card-title"> {{$get->name}} - {{$product->attributes[0]->option}}</h5>
                        </div>
                    </div>
                    </a>
                </div>
            @endforeach
        </div>

            {{ $products->links('vendor.pagination.bootstrap-4') }}

        </center>

    </div>
</div>

@stop

@section('js')
@stop

resources/views/dashboard/printInvoice.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Invoice Print</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">
</head>
<body>
<div class="wrapper">
    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-12">
                <h2 class="page-header">
                    <i class="fas fa-globe"></i> Invoice
                    <small class="float-right">Date: {{$data->created_at}}</small>
                </h2>
            </div>
            <!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                <address>
                    <strong>Admin.</strong><br>
                    <b>Customer : </b>{{$data->customers->name}}<br>
                </address>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Table row -->
        <div class="row">
            <div class="col-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Qty</th>
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Subtotal</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($carts as $cart)
                        <tr>
                            <td>{{$cart->qty}}</td>
                            <td>{{$cart->name}}</td>
                            <td>{{$cart->price}}</td>
                            <td>{{$cart->subTotal}}</td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <div class="row">
            <!-- accepted payments column -->
            <div class="col-6">

{{--                <p class="lead">Amount Due 2/22/2014</p>--}}
<p></p>
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th style="width:50%">Cash:</th>
                            <td>${{$data->amount_pay}}</td>
                        </tr>
                        <tr>
                            <th>Cash Paid</th>
                            <td>${{$data->amount_pay}}</td>
                        </tr>

                    </table>
                </div>

            </div>
            <!-- /.col -->
            <div class="col-6">
{{--                <p class="lead">Amount Due 2/22/2014</p>--}}
                <p></p>
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th style="width:50%">Subtotal:</th>
                            <td>${{$total}}</td>
                        </tr>
                        <tr>
                            <th>Total:</th>
                            <td>${{$total}}</td>
                        </tr>
                    </table>
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- ./wrapper -->
<!-- Page specific script -->
<script>
    window.addEventListener("load", window.print());
</script>
</body>
</html>