routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('s');


Auth::routes();

Route::get('/show', [\App\Http\Controllers\HomeController::class, 'show']);
Route::get('/showOne', [\App\Http\Controllers\HomeController::class, 'getOne']);
Route::get('/create', [\App\Http\Controllers\HomeController::class, 'create']);
Route::get('/updateProduct', [\App\Http\Controllers\HomeController::class, 'updateProduct']);
Route::get('/getCategory', [\App\Http\Controllers\HomeController::class, 'getCategory']);
Route::get('/createVarian', [\App\Http\Controllers\HomeController::class, 'createVarian']);
Route::get('/showVarian', [\App\Http\Controllers\HomeController::class, 'showVarian']);
Route::get('/createAttribute', [\App\Http\Controllers\HomeController::class, 'createAttribute']);
Route::get('/createOption', [\App\Http\Controllers\HomeController::class, 'createOption']);
Route::get('/order', [\App\Http\Controllers\HomeController::class, 'order']);
Route::get('/orderCart', [\App\Http\Controllers\HomeController::class, 'orderCart']);
Route::get('/order/destroy/{id}', [\App\Http\Controllers\HomeController::class, 'deleteCart'])->name('delete.cart');
Route::get('/customer', [\App\Http\Controllers\HomeController::class, 'showCustomer']);
Route::get('/report', [\App\Http\Controllers\HomeController::class, 'report']);
Route::get('/showAttribute', [\App\Http\Controllers\HomeController::class, 'showAttribute']);

Route::middleware(['auth'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::get('/pos', [App\Http\Controllers\HomeController::class, 'pos'])->name('pos');

    Route::post('/posSearch/', [App\Http\Controllers\HomeController::class, 'posSearch'])->name('pos.search');
    Route::get('/pos/variable/{id}', [App\Http\Controllers\HomeController::class, 'posVariable'])->name('posVariable');
    Route::get('/hold/{customer_id}', [App\Http\Controllers\HomeController::class, 'holdView'])->name('holdView');

    //Route::get('/expense', [App\Http\Controllers\HomeController::class, 'expense'])->name('expense');
    Route::get('/home/{filter}', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboardFilter');
    Route::get('actionCart/{name}/{price}/{product_id}/{variant_id}', [App\Http\Controllers\HomeController::class, 'actionCart'])->name('actionCart');

    Route::post('/updateQty', [\App\Http\Controllers\HomeController::class, 'updateQty'])->name('updateQty');
    Route::post('/getDiscount', [\App\Http\Controllers\HomeController::class, 'getDiscount']);

    Route::get('/totalPrice', [\App\Http\Controllers\HomeController::class, 'totalPrice'])->name('totalPrice');

    Route::post('/hold', [\App\Http\Controllers\HomeController::class, 'hold'])->name('hold');

    Route::post('/createCustomer', [\App\Http\Controllers\HomeController::class, 'createCustomer'])->name('createCustomer');
    Route::post('/createOrder', [\App\Http\Controllers\HomeController::class, 'createOrder'])->name('createOrder');

    Route::get('/printInvoice/{id}', [\App\Http\Controllers\HomeController::class, 'printInvoice'])->name('printInvoice');
    Route::get('/printShipping/{id}', [\App\Http\Controllers\HomeController::class, 'printShipping'])->name('printShipping');

    Route::get('/printLabel/{type}/{id}', [\App\Http\Controllers\HomeController::class, 'printLabel'])->name('printLabel');
    Route::get('/transaction', [\App\Http\Controllers\HomeController::class, 'transaction'])->name('transaction');

    //Route::group(['prefix'=>'products','as'=>'products.','middleware'=>'auth'], function(){
    Route::group(['prefix' => 'products', 'as' => 'products.', 'middleware' => 'auth'], function () {
        Route::get('/import', [App\Http\Controllers\ProductController::class, 'import'])->name('import');
        Route::post('/importAction', [App\Http\Controllers\ProductController::class, 'importAction'])->name('importAction');
        Route::get('/', [App\Http\Controllers\ProductController::class, 'index'])->name('index');
        Route::get('/edit/{id}', [App\Http\Controllers\ProductController::class, 'edit'])->name('edit');
        Route::post('/update/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('update');
        Route::get('/destroy/{id}', [App\Http\Controllers\ProductController::class, 'destroy'])->name('destroys');
        Route::get('/a/create', [\App\Http\Controllers\ProductController::class, 'create'])->name('create');
        Route::post('/a/create/post', [\App\Http\Controllers\ProductController::class, 'store'])->name('store');

        Route::get('/label', [App\Http\Controllers\ProductController::class, 'label'])->name('label');
        Route::get('/labelVariant/{id}', [App\Http\Controllers\ProductController::class, 'labelVariant'])->name('labelVariant');
        Route::get('/actionLabel/{id}/{name}/{price}', [App\Http\Controllers\ProductController::class, 'actionLabel'])->name('actionLabel');
        Route::post('/labelPrint', [App\Http\Controllers\ProductController::class, 'labelPrint'])->name('labelPrint');
        Route::get('/clear/label', [App\Http\Controllers\ProductController::class, 'clearLabel'])->name('clear.label');

        // Route::get('/', [App\Http\Controllers\ProductController::class, 'index'])->name('index');
    });


    Route::group(['prefix' => 'categories', 'as' => 'categories.', 'middleware' => 'auth'], function () {
        Route::get('/import', [App\Http\Controllers\CategoryController::class, 'import'])->name('import');
        Route::get('/{page}', [App\Http\Controllers\CategoryController::class, 'index'])->name('index');
        Route::get('/destroy/{id}', [App\Http\Controllers\CategoryController::class, 'destroy'])->name('destroys');
        Route::get('/a/create', [\App\Http\Controllers\CategoryController::class, 'create'])->name('create');
        Route::post('/store', [\App\Http\Controollers\CategoryController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [\App\Http\Controllers\CategoryController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [\App\Http\Controllers\CategoryController::class, 'update'])->name('update');

        Route::get('/', [App\Http\Controllers\CategoryController::class, 'index'])->name('index');
    });
    Route::get('expense/destroys/{id}', [App\Http\Controllers\ExpenseController::class, 'destroy'])->name('expense.destroys');
    Route::resource('expense',\App\Http\Controllers\ExpenseController::class);

    Route::get('discount/destroys/{id}', [App\Http\Controllers\DiscountController::class, 'destroy'])->name('discount.destroys');
    Route::resource('discount',\App\Http\Controllers\DiscountController::class);

    Route::get('users/destroys/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroys');
    Route::resource('users',\App\Http\Controllers\UserController::class);
});

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

//        dd($this->woocommerce()->get('products'));
        $data = $this->woocommerce()->get('products/categories');

//        dd($data);
        view()->share([
            'data' => $data
        ]);
        return view('dashboard.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = '';
        view()->share([
            'edit' => $edit
        ]);
        return view('dashboard.categories.form');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = [
            'name' => $request->name,
        ];

//        dd($request->name);

        try {
            $this->woocommerce()->post('products/categories', $data);

            return redirect()->route('categories.index')->with('success','success create data');
        } catch (\Exception $e) {
//            report($e);

            return redirect()->route('categories.create')->with('danger','fail create data');

        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = 'yes';
        $data = $this->woocommerce()->get('products/categories/'.$id);

        view()->share([
            'edit' => $edit,
            'data' => $data
        ]);
        return view('dashboard.categories.form');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        dd($id);
        $data = [
            'name' => $request->name
        ];

        $this->woocommerce()->put('products/categories/'.$id, $data);

        return redirect()->route('categories.index')->with('success','success edit data');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = $this->woocommerce()->delete('products/categories/'.$id, ['force' => true]);

        return redirect()->route('categories.index')->with('danger','success delete data');

    }
}

resources/views/dashboard/categories/form.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Category</h1>
@stop

@section('content')
    @include('dashboard.alert')

{{--    {{$edit}}--}}
    <section class="content">
        <form action="{{($edit == "yes") ? route('categories.update',$data->id) : route('categories.store') }}" method="post">
            @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="form-group">
                            <label for="inputName">Name</label>
                            <input type="text" name="name" id="inputName" value="{{($edit == "yes") ? $data->name : '' }}" class="form-control">
                        </div>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a href="#" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-success float-right"> Save </button>
            </div>
        </div>
        </form>
    </section>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/dashboard/categories/import.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>import</p>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/dashboard/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>List Categories</h1>
@stop

@section('content')
    @include('dashboard.alert')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Striped Full Width Table</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Name</th>
                    <th>Action</th>

                </tr>
                </thead>
                <tbody>
{{--                {{$i=1}}--}}
                @foreach($data as $a)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$a->name}}</td>

{{--                    <td>{!! $product->price_html !!}</td>--}}
                    <td><div class="btn-group">

                            <a href="{{route('categories.edit',$a->id)}}" class="btn btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{{route('categories.destroys',$a->id)}}" onclick="return confirm(`Are you sure?`)">
                                <button type="button" class="btn btn-danger">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </a>
                        </div>
                    </td>

                </tr>
                @endforeach

                </tbody>
                </table>
        </div>
{{--    {!! $products->links() !!}--}}

    <!-- /.card-body -->
        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
            </ul>
        </div>

    </div>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop